spring:
    datasource:
        username: root
        password: 3566108
        url: jdbc:mysql://192.168.196.0:3306/limysql
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource


mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        #map-underscore-to-camel-case: false #═Нит├Ч├ч




security:
    allow:
        paths: /**,/loginPage,/css/**,/fonts/**,/images/**,/js/**
    login:
        path: /user/login



